# 1. Reglas que queremos APAGAR
disabled_rules:
  - trailing_whitespace
  - function_body_length

# 2. Reglas de análisis profundo
analyzer_rules:
  - unused_import

# 3. Reglas opcionales que queremos PRENDER
opt_in_rules:
  - empty_count
  - colon
  - comma
  - force_unwrapping
  - force_try              # Te avisará si usas 'try!'
  - modifier_order
  - operator_usage_whitespace

# 4. Configuración personalizada de reglas
line_length:
  warning: 400
  error: 500

force_cast: warning
force_unwrapping: warning
force_try: warning         # Que sea advertencia para que no te tire la compilación

type_name:
  min_length: 3
  max_length: 40
  allowed_symbols: ["_"]

identifier_name:
  min_length: 3
  excluded:
    - id
    - x
    - y

# 5. Dónde debe mirar SwiftLint
included:
  - .

# 6. Qué debe ignorar
excluded:
  - DerivedData
  - Build
  - Pods
